name: Set up fmtc
description: Build and install fmtc VapourSynth plugin
inputs:
  fmtc-version:
    description: fmtc version
    required: true
runs:
  using: composite
  steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: fmtc-R${{ inputs.fmtc-version }}

    - name: Install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config build-essential

    - name: Checkout fmtc
      shell: bash
      run: |
        git clone https://gitlab.com/EleonoreMizo/fmtconv.git .fmtc
        pushd .fmtc
        git checkout "r${{ inputs.fmtc-version }}"
        popd
  
    - name: Build and install fmtc
      env:
        CC: ccache gcc
        CXX: ccache g++
      shell: bash
      run: |
        pushd .fmtc/build/unix
        ./autogen.sh
        ./configure --prefix=/usr --libdir=/usr/lib/vapoursynth
        make -j"$(nproc)"
        sudo make install
        popd
        rm -rf .fmtc

    - name: Verify fmtc install
      shell: python
      run: |
        import vapoursynth
        print(vapoursynth.core.fmtc)
